### ISSUE TITLE
Documentation for setup

### ISSUE THREAD

**Issue by makyo** [juliangiebel/SS14.MapServer#13]
It would be lovely to have a README with some simple setup instructions for Docker environments.

I have only worked with Docker a few times have not worked with Dotnet web apps at all, and am doing my level best to get the database working with the postgres container with little luck:

```
mapserver-map_database-1   | 
mapserver-map_database-1   | PostgreSQL Database directory appears to contain a database; Skipping initialization
mapserver-map_database-1   | 
mapserver-map_database-1   | 2024-04-21 18:45:21.994 UTC [1] LOG:  starting PostgreSQL 16.2 (Debian 16.2-1.pgdg120+2) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
mapserver-map_database-1   | 2024-04-21 18:45:21.994 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
mapserver-map_database-1   | 2024-04-21 18:45:21.994 UTC [1] LOG:  listening on IPv6 address "::", port 5432
mapserver-map_database-1   | 2024-04-21 18:45:22.008 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
mapserver-map_database-1   | 2024-04-21 18:45:22.019 UTC [28] LOG:  database system was shut down at 2024-04-21 18:43:13 UTC
mapserver-map_database-1   | 2024-04-21 18:45:22.035 UTC [1] LOG:  database system is ready to accept connections
mapserver-ss14mapserver-1  | Unhandled exception. System.ArgumentException: Host can't be null
mapserver-ss14mapserver-1  |    at Npgsql.NpgsqlConnectionStringBuilder.PostProcessAndValidate()
mapserver-ss14mapserver-1  |    at Npgsql.NpgsqlSlimDataSourceBuilder.PrepareConfiguration()
mapserver-ss14mapserver-1  |    at Npgsql.NpgsqlSlimDataSourceBuilder.Build()
mapserver-ss14mapserver-1  |    at Npgsql.NpgsqlDataSourceBuilder.Build()
mapserver-ss14mapserver-1  |    at Program.<Main>$(String[] args) in /src/SS14.MapServer/Program.cs:line 65
mapserver-ss14mapserver-1  |    at Program.<Main>(String[] args)
```

which is pretty clearly a config goof on my part, but I am unsure of how to get that into the app properly, even by attempting to fudge a connection string in the appropriate `appsettings.*.yaml` file.

**Comment by juliangiebel** [comment]
Yea I definitely need to write some documentation for hosting this. 👍
